### ISSUE TITLE
garfield-user should return 0 on success

### ISSUE THREAD

**Issue by jduepmeier** [kitinfo/garfield-shell#12]
At least the ```garfield-user history``` returns not 0 on success. The most shells see a non-zero exit code as failure.

**Comment by cbdevnet** [comment]
The `history` mode returns the number of items read as return value. Not sure if that information is useful.

**Comment by cbdevnet** [comment]
With d5ae8efd18c61ad135581ce7d80443a51d2a5caf, all garfield-user modes return 0 on success.
